### ISSUE TITLE
Use Flask to build the web-app

### ISSUE THREAD

**Issue by Aryan-2003** [PCON-Hacktoberfest-2022/Movie-Recommendation-System#1]
Change the web-framework from streamlit to flask and enhance the frontend as well

**Comment by deathsurgeon1** [comment]
Hey @Aryan-2003 , i can add Flask backend API and host the same on heroku. Let me know in case this is fine.

**Comment by Aryan-2003** [comment]
Ok @deathsurgeon1 you can proceed.
