### ISSUE TITLE
Better Similarity between the movies

### ISSUE THREAD

**Issue by Aryan-2003** [PCON-Hacktoberfest-2022/Movie-Recommendation-System#2]
I have used cosine_similarity in the project, so the goal is to use some other method and try to find out the better similarity between the movies.

**Comment by deathsurgeon1** [comment]
Hi @Aryan-2003 , I would like to work on this

**Comment by Aryan-2003** [comment]
ok @deathsurgeon1 you can work on this

**Comment by deathsurgeon1** [comment]
Hi @Aryan-2003 , I have completed the task for recommending movies for a given input movie. How should I compare my results to existing results? Do you have some examples where recommendations were not as expected. I can try those movies.

**Comment by Aryan-2003** [comment]
Have you used the same dataset?

**Comment by deathsurgeon1** [comment]
yes

**Comment by Aryan-2003** [comment]
So just send me the 5 best similarity score of 1st five movies here
If those will be better then your model will be good

**Comment by Aryan-2003** [comment]
Since the similarity matrix is 4806x4806 then it is not possible to check for each one

**Comment by deathsurgeon1** [comment]
sure

**Comment by Aryan-2003** [comment]
or you can send the pull request I will check it

**Comment by deathsurgeon1** [comment]
Output:

`Input movie:  Avatar
Recommendations:
('Aliens', 0.6170014)
('The Abyss', 0.5810454)
('Prometheus', 0.5806612)
('The Inhabited Island', 0.5791716)
('Guardians of the Galaxy', 0.57117456)

Input movie:  Pirates of the Caribbean: At World's End
Recommendations:
("Pirates of the Caribbean: Dead Man's Chest", 0.59608173)
('Pirates of the Caribbean: The Curse of the Black Pearl', 0.5891819)
('Poseidon', 0.57035935)
('The Life Aquatic with Steve Zissou', 0.5539963)
('Cutthroat Island', 0.5499933)

Input movie:  Spectre
Recommendations:
('Skyfall', 0.744504)
('GoldenEye', 0.6840049)
('Die Another Day', 0.6703752)
('Octopussy', 0.65326357)
('The Timber', 0.65046)

Input movie:  The Dark Knight Rises
Recommendations:
('The Dark Knight', 0.7334488)
('Batman Begins', 0.7325363)
('Batman Returns', 0.7296431)
('Batman', 0.6966487)
('Batman v Superman: Dawn of Justice', 0.6964006)

Input movie:  John Carter
Recommendations:
('Planet of the Apes', 0.5374572)
('The Martian', 0.5073267)
('Treasure Planet', 0.4824682)
("Pirates of the Caribbean: At World's End", 0.4669356)
('Cat on a Hot Tin Roof', 0.44989353)

Input movie:  Spider-Man 3
Recommendations:
('Spider-Man 2', 0.7517333)
('Spider-Man', 0.6564461)
('The Amazing Spider-Man 2', 0.6054206)
('The Amazing Spider-Man', 0.6046483)
('Ant-Man', 0.54928845)`

**Comment by Aryan-2003** [comment]
I have asked you to send similarity score also i.e how much movies are similar 
so edit it add similarity score as well for each movies

**Comment by deathsurgeon1** [comment]
Added score as well.

**Comment by Aryan-2003** [comment]
Yes that's looking very well compared to my score

**Comment by Aryan-2003** [comment]
It's nice
you can send the pr

**Comment by deathsurgeon1** [comment]
sure, I was testing in the existing notebook itself. I will share the notebook changes with separate blocks for additional change I did.

**Comment by Aryan-2003** [comment]
ok

**Comment by deathsurgeon1** [comment]
Raised a PR . Please review @Aryan-2003

**Comment by Aryan-2003** [comment]
ok

**Comment by Aryan-2003** [comment]
So you have used embedding layers to generate vectors i.e a deep learning method and then applied cosine_similarity.

Ok I have merged it.

**Comment by deathsurgeon1** [comment]
cool, thanks!!

**Comment by Aryan-2003** [comment]
@deathsurgeon1 just check once that it has been merged or not and whether it is showing on your hacktoberfest profile or not.

**Comment by deathsurgeon1** [comment]
Hey @Aryan-2003 , you need to hactoberfest-accepted label as well to my PR.

**Comment by deathsurgeon1** [comment]
Also you need to add some approval comment in PR

**Comment by Aryan-2003** [comment]
@deathsurgeon1 now?

**Comment by deathsurgeon1** [comment]
yeah now it is showing up correctly. Thanks!!
